rvm:
  - 2.2.2
  - 2.2.3

branches:
  only:
    - master

notifications:
  email:
    recipients:
       - mathijs.sterk@itrp.com
       - robin.roestenburg@itrp.com
    on_success: change
    on_failure: always
